# Generated by Django 4.2.1 on 2023-06-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="show_homepage",
            field=models.BooleanField(default=False),
        ),
    ]
