# Generated by Django 4.2.1 on 2023-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_productcategory_show_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_homepage",
            field=models.BooleanField(default=False),
        ),
    ]
