# Generated by Django 4.2.1 on 2023-06-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_show_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                related_name="product_tags", to="product.producttags"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="variation",
            field=models.ManyToManyField(
                related_name="product_variations", to="product.productvariation"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="product.product",
            ),
        ),
    ]
