# Generated by Django 4.2.1 on 2023-06-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_tags_alter_product_variation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="product.producttags"),
        ),
        migrations.AlterField(
            model_name="product",
            name="variation",
            field=models.ManyToManyField(to="product.productvariation"),
        ),
    ]
