# Generated by Django 4.2.1 on 2023-06-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0001_initial"),
        ("product", "0007_alter_product_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_brand",
                to="brand.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                related_name="product_tags", to="product.producttags"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="variation",
            field=models.ManyToManyField(
                related_name="product_variations", to="product.productvariation"
            ),
        ),
    ]
