# Generated by Django 4.2.1 on 2023-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0002_remove_payment_status_remove_payment_transaction_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
