# Generated by Django 4.2.1 on 2023-06-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
