# Generated by Django 4.2.1 on 2023-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="testimonial")),
                ("name", models.CharField(max_length=255)),
                ("comment", models.TextField()),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
