# Generated by Django 4.2.1 on 2023-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="sub_title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
