# Generated by Django 4.2.1 on 2023-06-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_blog_sub_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="sub_title",
            field=models.TextField(max_length=123),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=29),
        ),
    ]
