# Generated by Django 4.1.3 on 2023-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_blog_popular_blog_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=13)),
                ("message", models.TextField()),
            ],
        ),
    ]
