# Generated by Django 4.1.3 on 2023-06-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="variation",
        ),
    ]
