# Generated by Django 4.1.3 on 2023-06-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_wishlist_quantity_remove_wishlist_variation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={"verbose_name": "Wish List", "verbose_name_plural": "Wish Lists"},
        ),
    ]
