# Generated by Django 4.2.1 on 2023-06-09 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 9, 17, 43, 44, 466683)
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In-progress", "In-progress"),
                    ("Delivered", "Delivered"),
                    ("canceled", "canceled"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="razor_pay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="user_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="mobile",
            field=models.CharField(max_length=13),
        ),
    ]
