# Generated by Django 4.1.3 on 2023-06-09 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_date_time_remove_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 9, 19, 43, 31, 336492)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="mobile",
            field=models.CharField(max_length=13, null=True),
        ),
    ]
