# Generated by Django 4.1.3 on 2023-06-09 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_date_alter_order_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 9, 19, 43, 44, 315823)
            ),
        ),
    ]
