# Generated by Django 4.1.3 on 2023-06-10 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 10, 19, 33, 22, 701413)
            ),
        ),
    ]
