# Generated by Django 4.2.1 on 2023-06-12 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_alter_order_date_alter_orderdetails_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 12, 17, 58, 0, 226819)
            ),
        ),
    ]
