# Generated by Django 4.2.1 on 2023-06-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_alter_order_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
    ]
