# Generated by Django 4.2.1 on 2023-06-14 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_remove_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 14, 22, 9, 30, 408474)
            ),
        ),
    ]
